### PR TITLE
Update cdv-generic-nav-bar.hbs for new Ember style

### PR DESCRIPTION
**Pull request by OpakAlex**

### CODE REVIEW

**Comment by AW-UC** [comment]
@OpakAlex Thanks, but how about adapting https://github.com/poetic/ember-cli-cordova/blob/master/tests/integration/nav-bar-test.js ? I think this should be included in the PR.

**Comment by OpakAlex** [comment]
i think my PR can be close, and you can put it's small fixes without PR :)

**Comment by AW-UC** [comment]
@OpakAlex Why close? Of course one can fix this without the PR, but this change will be needed in the future. So it has to be merged! :-)

**Comment by OpakAlex** [comment]
We need PR with ember update, and include this. so for now we closed this PR because it's only update code, without update ember.

**Comment by AW-UC** [comment]
allright!

**Pull request closed without merging**
